version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lendflow-app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lendflow_db
      - DB_USERNAME=lendflow_user
      - DB_PASSWORD=lendflow_pass
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: lendflow-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lendflow_db
      - MYSQL_USER=lendflow_user
      - MYSQL_PASSWORD=lendflow_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lendflow-queue
    command: php artisan queue:work --tries=3 --sleep=3
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lendflow
      - DB_USERNAME=root
      - DB_PASSWORD=root
volumes:
  db_data:
